name = input("Enter your full name: ")
student_id = input("Enter your student ID: ")
department = input("Enter your department: ")
github_user = input("Enter your GitHub username: ")
programming_goal = input("Enter one programming goal: ")
print("\n--- Student Profile ---")
print(f"Name: {name}")
print(f"Department: {department}")
print(f"Age: {github_user}")
print(f"Career Goal: {programming_goal}")
